---
- name: "Add nodejs from Nodesource"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | bash -
    apt-get install -y nodejs

- name: "Install pm2"
  npm:
    name: pm2
    global: yes