---
- name: "Add nodejs from Nodesource"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    apt-get install -y nodejs
    sudo npm install --global n
    sudo n 13.8.0

- name: "Install pm2"
  npm:
    name: pm2
    global: yes