---
- name: "Add nodejs from Nodesource"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    apt-get install -y nodejs


- name: "Install nodejs 13"
  become: true
  apt:
    name: ["nodejs","npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  npm:
    name: pm2
    global: yes