---
- name: "backend app directory Creation"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchiving back-end files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Install Nodejs Dependencies"
  shell: |
    cd ~/backend-app
    npm i

- name: "Execute Nodejs app with pm2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: stdout
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configuring pm2 to start as a service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save